#pragma once

// From glfw3.h
#define JNGL_MOUSE_BUTTON_1         0
#define JNGL_MOUSE_BUTTON_2         1
#define JNGL_MOUSE_BUTTON_3         2
#define JNGL_MOUSE_BUTTON_4         3
#define JNGL_MOUSE_BUTTON_5         4
#define JNGL_MOUSE_BUTTON_6         5
#define JNGL_MOUSE_BUTTON_7         6
#define JNGL_MOUSE_BUTTON_8         7
#define JNGL_MOUSE_BUTTON_LAST      JNGL_MOUSE_BUTTON_8
#define JNGL_MOUSE_BUTTON_LEFT      JNGL_MOUSE_BUTTON_1
#define JNGL_MOUSE_BUTTON_RIGHT     JNGL_MOUSE_BUTTON_2
#define JNGL_MOUSE_BUTTON_MIDDLE    JNGL_MOUSE_BUTTON_3
